build:
  script:
    - "cp -ru /cache/root/.android /cache/root/.gradle /cache/root/.profile /cache/root/android-sdk-linux /root/ 2>/dev/null || :"
    - mkdir -p ~/.gradle/
    - cd /builds/mycelium/mycelium-com-wallet
    - echo working on branch $CI_BUILD_REF_NAME''
    - "if [ $CI_BUILD_REF_NAME'' == 'master' ]; then gradleParam=''; else gradleParam='-PskipProguard'; fi"
    - ./gradlew clean test lint build $gradleParam -Pbranch=$CI_BUILD_REF_NAME''
    - "mkdir /cache/root 2>/dev/null || :"
    - cp -ru /root/.android /root/.gradle /root/.profile /root/android-sdk-linux /cache/root
  type: build
  artifacts:
    expire_in: 4 weeks
    paths:
      - ./**/build/reports/
      - ./**/build/outputs/
      - LVL/build/reports/
      - bitlib/build/reports/
      - btchip/build/reports/
      - coinapult/build/reports/
      - lt-api/build/reports/
      - libs/zxing-android/build/reports/
      - libs/nordpol/build/reports/
      - mbw/build/outputs/logs/
      - mbw/build/outputs/apk/mbw-btctestnet-debug-*build*.apk
      - mbw/build/reports/
      - mbwlib/build/reports/
      - trezor/build/outputs/
      - trezor/build/reports/
      - wapi/build/reports/

  tags:
    - 4GB_RAM
